# Generated by Django 6.0 on 2025-12-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('cardiology', 'cardiology'), ('neurology', 'neurology'), ('orthopedics', 'orthopedics'), ('pediatries', 'pediatries'), ('gynecology', 'gynecology')], max_length=50)),
                ('doctor', models.CharField(choices=[('dr_amit', 'dr. Amit Sharma'), ('dr_rahul', 'dr. rahul Verma'), ('dr_neha', 'dr. neha Singh'), ('dr_pooja', 'dr. Pooja Gupta')], max_length=50)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('full_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ia_active', models.BooleanField(default=True)),
            ],
        ),
    ]
